<a href="https://colab.research.google.com/github/Leirbag15/AM-Lista1/blob/main/7_Filtragem_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7 - Filtragem de dados
Filtragem de dados é uma tarefa importantíssima na vida de qualquer cientista de dados. Nessa seção, veremos como criar filtros em um conjunto de dados utilizando o Pandas.

## Operadores booleanos

### and

In [1]:
x = 12

In [2]:
x > 5 and x < 15

True

### or

In [3]:
y = 5

In [4]:
y < 7 or y > 13

True

### not

In [5]:
not True

False

In [6]:
not False

True

### Numpy

In [7]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [8]:
bmi > 21

array([ True, False,  True,  True,  True])

In [11]:
bmi > 21 and bmi< 22

ValueError: ignored

In [12]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [13]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

In [22]:
#1
np_age = np.array([32,45,21,20,26])
print(np_age > 21)
print(np.logical_and(np_age >20, np_age<30))
print (np_age[np.logical_and(np_age >20, np_age<30)])
#É possível usar arrays Numpy para simplificar diversas operações lógicas e até seleções

[ True  True False False  True]
[False False  True False  True]
[21 26]


## Filtrando um DataFrame Pandas

In [15]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col=0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

**Objetivo**: selecionar os países com área maior do que 8 milhões de km2

3 passos:
- Selecionar a coluna "area"
- Fazer uma comparação na coluna "area"
- Usar o resultado para selecionar os países

In [23]:
# Selecionar a coluna "area"
brics['area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [24]:
# Fazer uma comparação na coluna "area"
brics['area'] > 8
is_huge = brics['area'] > 8
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [25]:
# Usar o resultado para selecionar os países
brics[is_huge]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [34]:
#2
brics2 = pd.read_csv("brics.csv", index_col = 0)
print(brics2['population'])
print(brics2['population'] > 200)
is_large = brics2['population'] > 200
print(brics2[is_large])
#DataFrames do Panda possuem diversos recursos para visualização e seleção de dados
#seleções podem ser guardadas em variaveis e usadas em outros contextos

BR     200.40
RU     143.50
IN    1252.00
CH    1357.00
SA      52.98
Name: population, dtype: float64


country    capital   area  population
BR  Brazil   Brasilia  8.516       200.4
IN   India  New Delhi  3.286      1252.0
CH   China    Beijing  9.597      1357.0

In [27]:
# Importando dataset de carros
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [36]:
# Extraia a coluna 'drives_right' do DataFrame 'cars' e atribua a variável 'dr'
dr = cars['drives_right']

# Use a variável 'dr' para criar um subconjunto de dados chamado 'sel'
sel = cars[dr]

# Imprima a variável 'sel'
print(sel)

     cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True


In [37]:
# Crie uma variável car_maniac: linhas que possuem 'cars_per_cap' maiores do que 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Imprima 'car_maniac'
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False


In [35]:
# Importe o conjunto de dados 'cars.csv', bem como as bibliotecas 'pandas' e 'numpy'
import pandas as pd
import numpy as np
cars = pd.read_csv('cars.csv', index_col = 0)

# Crie a variável 'medium': linhas que possuem 'cars_per_cap' entre 100 e 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Imprima 'medium'
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True


In [39]:
#3
cars2 = pd.read_csv('cars.csv', index_col = 0)
cpc2 = cars2['cars_per_cap']
between2 = np.logical_and(cpc2 > 200, cpc2<800)
medium2 = cars2[between2]
print(medium2)
#é possível combinar recursos de pandas e numpy para criar seleções simples e diretas


     cars_per_cap    country  drives_right
AUS           731  Australia         False
JAP           588      Japan         False
